Layout/ClassStructure:
  Enabled: true
Layout/FirstArgumentIndentation:
  EnforcedStyle: consistent
Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent
Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent
Layout/FirstArrayElementLineBreak:
  Enabled: true
Layout/FirstHashElementLineBreak:
  Enabled: true
Layout/FirstMethodArgumentLineBreak:
  Enabled: true
Layout/FirstMethodParameterLineBreak:
  Enabled: true
Layout/MultilineArrayLineBreaks:
  Enabled: true
Layout/MultilineHashKeyLineBreaks:
  Enabled: true
Layout/MultilineMethodArgumentLineBreaks:
  Enabled: true
Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Metric/BlockLength:
  Max: 100
Metric/ClassLength:
  Max: 284
Metric/MethodLength:
  Max: 50
Metric/AbcSize:
  Max: 50
Metric/CyclomaticComplexity:
  Max: 10

Naming/InclusiveLanguage:
  Enabled: false

Style/AccessorGrouping:
  Enabled: false
Style/ClassAndModuleChildren:
  EnforcedStyle: compact
Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/SymbolArray:
  EnforcedStyle: brackets
